### ISSUE TITLE
[Suggestion]: Make hunger poison you

### ISSUE THREAD

**Issue by StellaBiscuit** [Mrbysco/ClassicFood#1]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Due to how the mod work, the hunger effect does nothing, so eating rotten flesh or raw chicken has no negatives and rotten flesh becomes a ok healing item

It would be great if hunger caused poison at a simillar speed to normal hunger

**Comment by Mrbysco** [comment]
Has been added in 7.1.0
